openapi: 3.0.0

info:
  title: Maple
  description: |
    An API to store links to the music, that the user likes, over the cloud.
    Allowing the user to safekeep the music he likes, organize them with tags and search through them

  version: 0.0.1

paths:
  /music:
    get: {} # gets a paginated list of all the songs
    post: {} # adds a song to the storage

  /music/{id}:
    get: {} # gets the info about the song for the given id
    put: {} # updates the songs by the id
    delete: {} # deletes a song by the given id

  /music/tags:
    get: {} # gets the list of 

  /music/{tag}:
    get: {} # gets all the songs by the given tag

  /music/search:
    get: {} # searches through the user's music in a feasibly smart way

components:
  schemas:
    Tag:
      type: object
      properties:
        value:
          type: string
    
    MusicMeta:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        client:
          type: string

    MusicData:
      type: object
      properties:
        url:
          type: string
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"

    Music:
      type: object
      properties:
        id:
          type: string
        data:
          $ref: "#/components/schemas/MusicData"
        meta:
          $ref: "#/components/schemas/MusicMeta"