openapi: 3.0.0

info:
  title: Maple
  description: |
    An API to store links to the music, that the user likes, over the cloud.
    Allowing the user to safekeep the music he likes, organize them with tags and search through them

  version: 0.0.1

paths:
  /music/storage:
    get: {} # gets a paginated list of all the songs
    post: {} # adds a song to the storage

  /music/{id}:
    get: {} # gets the info about the song for the given id
    put: {} # updates the songs by the id
    delete: {} # deletes a song by the given id

  /music/tags:
    get: {} # gets the list of 

  /music/{tag}:
    get: {} # gets all the songs by the given tag

  /music/search:
    get: {} # searches through the user's music in a feasibly smart way